In [2]:
#Data Collection
import nltk
nltk.download('gutenberg')
from nltk.corpus import gutenberg
import pandas as pd

#load dataset
data = gutenberg.raw('shakespeare-hamlet.txt')

with open('hamlet.txt','w') as file:
    file.write(data)

[nltk_data] Error loading gutenberg: <urlopen error [WinError 10060] A
[nltk_data]     connection attempt failed because the connected party
[nltk_data]     did not properly respond after a period of time, or
[nltk_data]     established connection failed because connected host
[nltk_data]     has failed to respond>


In [3]:
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from sklearn.model_selection import train_test_split

with open('hamlet.txt','r') as file:
    text = file.read().lower()

tokenizer = Tokenizer()
print([text])
tokenizer.fit_on_texts([text])
print(len(tokenizer.word_index))
total_words = len(tokenizer.word_index)+1

["[the tragedie of hamlet by william shakespeare 1599]\n\n\nactus primus. scoena prima.\n\nenter barnardo and francisco two centinels.\n\n  barnardo. who's there?\n  fran. nay answer me: stand & vnfold\nyour selfe\n\n   bar. long liue the king\n\n   fran. barnardo?\n  bar. he\n\n   fran. you come most carefully vpon your houre\n\n   bar. 'tis now strook twelue, get thee to bed francisco\n\n   fran. for this releefe much thankes: 'tis bitter cold,\nand i am sicke at heart\n\n   barn. haue you had quiet guard?\n  fran. not a mouse stirring\n\n   barn. well, goodnight. if you do meet horatio and\nmarcellus, the riuals of my watch, bid them make hast.\nenter horatio and marcellus.\n\n  fran. i thinke i heare them. stand: who's there?\n  hor. friends to this ground\n\n   mar. and leige-men to the dane\n\n   fran. giue you good night\n\n   mar. o farwel honest soldier, who hath relieu'd you?\n  fra. barnardo ha's my place: giue you goodnight.\n\nexit fran.\n\n  mar. holla barnardo\n\n   bar.

In [4]:
input_sequenes=[]

for line in text.split('\n'):
    token_list = tokenizer.texts_to_sequences([line])[0]
    print(token_list)
    for i in range(1,len(token_list)):
        n_gram_sequence = token_list[:i+1]
        print(n_gram_sequence)
        input_sequenes.append(n_gram_sequence)

print(input_sequenes)


[1, 687, 4, 45, 41, 1886, 1887, 1888]
[1, 687]
[1, 687, 4]
[1, 687, 4, 45]
[1, 687, 4, 45, 41]
[1, 687, 4, 45, 41, 1886]
[1, 687, 4, 45, 41, 1886, 1887]
[1, 687, 4, 45, 41, 1886, 1887, 1888]
[]
[]
[1180, 1889, 1890, 1891]
[1180, 1889]
[1180, 1889, 1890]
[1180, 1889, 1890, 1891]
[]
[57, 407, 2, 1181, 177, 1892]
[57, 407]
[57, 407, 2]
[57, 407, 2, 1181]
[57, 407, 2, 1181, 177]
[57, 407, 2, 1181, 177, 1892]
[]
[407, 1182, 63]
[407, 1182]
[407, 1182, 63]
[408, 162, 377, 21, 247, 882]
[408, 162]
[408, 162, 377]
[408, 162, 377, 21]
[408, 162, 377, 21, 247]
[408, 162, 377, 21, 247, 882]
[18, 66]
[18, 66]
[]
[451, 224, 248, 1, 30]
[451, 224]
[451, 224, 248]
[451, 224, 248, 1]
[451, 224, 248, 1, 30]
[]
[408, 407]
[408, 407]
[451, 25]
[451, 25]
[]
[408, 6, 43, 62, 1893, 96, 18, 566]
[408, 6]
[408, 6, 43]
[408, 6, 43, 62]
[408, 6, 43, 62, 1893]
[408, 6, 43, 62, 1893, 96]
[408, 6, 43, 62, 1893, 96, 18]
[408, 6, 43, 62, 1893, 96, 18, 566]
[]
[451, 71, 51, 1894, 567, 378, 80, 3, 273, 1181]
[451, 71]

In [5]:
max_len = max(len(x) for x in input_sequenes)
max_len

14

In [6]:
input_sequenes = np.array(pad_sequences(input_sequenes,maxlen=max_len,padding='pre'))
input_sequenes

array([[   0,    0,    0, ...,    0,    1,  687],
       [   0,    0,    0, ...,    1,  687,    4],
       [   0,    0,    0, ...,  687,    4,   45],
       ...,
       [   0,    0,    0, ...,    4,   45, 1047],
       [   0,    0,    0, ...,   45, 1047,    4],
       [   0,    0,    0, ..., 1047,    4,  193]],
      shape=(25732, 14), dtype=int32)

In [7]:
import tensorflow as tf

x,y = input_sequenes[:,:-1] , input_sequenes[:,-1]
print(x)
print(y)

[[   0    0    0 ...    0    0    1]
 [   0    0    0 ...    0    1  687]
 [   0    0    0 ...    1  687    4]
 ...
 [   0    0    0 ...  687    4   45]
 [   0    0    0 ...    4   45 1047]
 [   0    0    0 ...   45 1047    4]]
[ 687    4   45 ... 1047    4  193]


In [8]:
y = tf.keras.utils.to_categorical(y,num_classes=total_words)
print(y)
print(len(y[0]))

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
4818


In [9]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

In [10]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,LSTM,Dense,Dropout

model = Sequential()
model.add(Embedding(total_words,100,input_length=max_len-1))
model.add(LSTM(150,return_sequences=True))
model.add(Dropout(0.2))
model.add(LSTM(100))
model.add(Dense(total_words,activation='softmax'))

c:\Users\vaibh\Python\ANN Classification\venv\Lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [11]:
model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])
model.build(input_shape=(None, max_len))
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 14, 100)        │       481,800 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ (None, 14, 150)        │       150,600 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 14, 150)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_1 (LSTM)                   │ (None, 100)            │       100,400 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 4818)           │       486,618 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,219,418 (4.65 MB)

 Trainable params: 1,219,418 (4.65 MB)

 Non-trainable params: 0 (0.00 B)

In [12]:
history = model.fit(x_train,y_train,validation_data=(x_test,y_test),epochs=100,verbose=1)


Epoch 1/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 20s 24ms/step - accuracy: 0.0325 - loss: 6.9039 - val_accuracy: 0.0359 - val_loss: 6.7721
Epoch 2/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 14s 22ms/step - accuracy: 0.0392 - loss: 6.4605 - val_accuracy: 0.0394 - val_loss: 6.8821
Epoch 3/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 14s 22ms/step - accuracy: 0.0474 - loss: 6.3057 - val_accuracy: 0.0449 - val_loss: 6.8891
Epoch 4/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 14s 22ms/step - accuracy: 0.0520 - loss: 6.1642 - val_accuracy: 0.0470 - val_loss: 6.9085
Epoch 5/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 14s 22ms/step - accuracy: 0.0560 - loss: 6.0334 - val_accuracy: 0.0505 - val_loss: 6.9813
Epoch 6/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 16s 25ms/step - accuracy: 0.0634 - loss: 5.8983 - val_accuracy: 0.0538 - val_loss: 7.0155
Epoch 7/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 26s 40ms/step - accuracy: 0.0686 - loss: 5.7674 - val_accuracy: 0.0571 - val_loss: 7.0908
Epoch 8/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 16s 24ms/step - accuracy: 0.0789 - loss: 5

In [17]:
def predict_next_word(model,tokenizer,text,max_sequence_len):
    token_list = tokenizer.texts_to_sequences([text])[0]
    print('Token_List',token_list)
    if(len(token_list)>=max_sequence_len):
        token_list = token_list[-(max_sequence_len-1):]
    token_list = pad_sequences([token_list],maxlen=max_sequence_len-1,padding='pre')
    print('After pad sequences',token_list)
    predicted = model.predict(token_list,verbose=0)
    print(predicted)
    predicted_word_index = np.argmax(predicted,axis=1)
    for word,index in tokenizer.word_index.items():
        if index == predicted_word_index:
            return word
    return None



In [20]:
input_text = "Barn. Haue you had quiet"
print(f"Input Text:{input_text}")
max_sequence_len = model.input_shape[1]+1
next_word = predict_next_word(model,tokenizer,input_text,max_sequence_len)
print(f"Next word Predicted : {next_word}")


Input Text:Barn. Haue you had quiet
Token_List [346, 29, 6, 108, 568]
After pad sequences [[  0   0   0   0   0   0   0   0   0 346  29   6 108 568]]
[[2.2710015e-12 5.6991394e-07 3.4577573e-07 ... 2.5127398e-15
  7.7121464e-13 2.4243212e-12]]
Next word Predicted : guard


In [22]:
model.save('next_word_lstm.keras')

import pickle

with open('tokenizer.pickle','wb') as handle:
    pickle.dump(tokenizer,handle,protocol=pickle.HIGHEST_PROTOCOL)